export default [
  1,
  101,
  10101,
  10102,
  10103,
  '10103:add',
  10104,
  1010401,
  1010402,
  '1010401:add', // 按钮权限
  // '1010401:update',
  '1010401:delete',
  '1010401:query',
  1010403,
  2,
  201,
  202,
  203,
];

// 以路由名作为权限路由匹配字段
export const permissionRouteNames = [
  'autoroutes',
  'autoroutes_router',
  'autoroutes_router_introduce',
  'autoroutes_router_config',
  'autoroutes_router_meta',
  'autoroutes_router_meta:add',
  'autoroutes_router_group',
  'autoroutes_router_group_permission',
  'autoroutes_router_group_permission:add',
  // 'autoroutes_router_group_permission:delete',
  'autoroutes_router_group_permission:update', // 按钮权限
  'autoroutes_router_group_permission:query',
  'myAsyncPage',
  'autoroutes_router_group_hidden',
  'packages',
  'packages_jsonschema',
  'packages_neural',
  'packages_grittyui',
];

export const permissionRoutes = [
  {
    id: 1,
    type: 'dir',
    title: '自动路由',
    icon: 'route',
    name: 'autoroutes',
    path: '/autoroutes',
    children: [
      {
        id: 101,
        type: 'page',
        icon: 'route',
        name: 'autoroutes_router',
        path: '/autoroutes/router',
        title: '路由管理',
        children: [
          {
            id: 10101,
            type: 'page',
            icon: 'route',
            name: 'autoroutes_router_introduce',
            path: '/autoroutes/introduce',
            title: '路由介绍',
          },
          {
            id: 10102,
            type: 'page',
            icon: 'route',
            name: 'autoroutes_router_config',
            path: '/autoroutes/config',
            title: '路由配置',
          },
          {
            id: 10103,
            type: 'page',
            icon: 'route',
            name: 'autoroutes_router_meta',
            path: '/autoroutes/meta',
            title: '路由元数据',
          },
          {
            id: 10104,
            type: 'group',
            icon: 'route',
            name: 'autoroutes_router_group',
            path: '/autoroutes/group',
            title: '路由分组',
            children: [
              {
                id: 1010401,
                type: 'page',
                icon: 'route',
                name: 'autoroutes_router_group_permission',
                path: '/autoroutes/permission',
                title: '路由权限',
              },
              {
                id: 1010402,
                type: 'page',
                icon: 'route',
                name: 'myAsyncPage',
                path: '/autoroutes/async/:id*/:name+',
                title: '动态路由',
              },
              {
                id: 1010403,
                type: 'page',
                icon: 'route',
                name: 'autoroutes_router_group_hidden',
                path: '/autoroutes/hidden',
                title: '路由隐藏',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    type: 'dir',
    title: '包管理',
    icon: 'packages',
    name: 'packages',
    path: '/packages',
    children: [
      {
        id: 201,
        type: 'page',
        icon: 'jsonSchema',
        name: 'packages_jsonschema',
        path: '/packages/jsonschema',
        title: 'JSON Schema编辑器',
      },
      {
        id: 202,
        type: 'page',
        icon: 'graph',
        name: 'packages_neural',
        path: '/packages/neural',
        title: '神经网络',
      },
      {
        id: 203,
        type: 'page',
        icon: 'library',
        name: 'packages_grittyui',
        path: '/packages/grittyui',
        title: 'Gritty UI',
      },
    ],
  },
];
