/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Form: typeof import('./src/components/form/Form.vue')['default']
    FormItem: typeof import('./src/components/form/FormItem.vue')['default']
    Icon: typeof import('./src/components/icon/icon.vue')['default']
    Toolbar: typeof import('./src/components/toolbar/Toolbar.vue')['default']
  }
}
